using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CD01.Migrations
{
    /// <inheritdoc />
    public partial class Condo : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Rooms",
                columns: table => new
                {
                    RO_CODE = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    RO_PROJ = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DEPT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FLOOR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_ROOM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_HOMENO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_TYPE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_AREA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_RATIO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DATEIN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_SELECT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_ARAMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FLAG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_BF = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CR = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_ARNO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_MEA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_ELECNO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_METERWT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_METEREL = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CARPARK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_OWNER = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_RATE0 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST0 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST1TY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST2TY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUST3TY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LEASENO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN1TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN2TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN3TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN4TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN5TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN6TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN7TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN8TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN9TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN1AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN2AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN3AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN4AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN5AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN6AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN7AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN8AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN9AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_STATUS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_RTYPE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_REMARK = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVNAME1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVADDR1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVTEL1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVID1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVNAME2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVADDR2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVTEL2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVID2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVNAME3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVADDR3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVTEL3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVID3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVNAME4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVADDR4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVTEL4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVID4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVNAME5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVADDR5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVTEL5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVID5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LASTRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LASTRCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LASTRCA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DATEIN2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EDIT_DATE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EDIT_TIME = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EDIT_BY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FIELD1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FIELD2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FIELD3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FIELD4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_RCODE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_RSTATUS = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_JONG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_JONGD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_MOVEIN = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_INDATE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_SANYA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_SANYAD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_BEOUT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_BEOUTD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_OUT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_OUTD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_REMARK2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_RDATE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX1QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX2QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX3QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX4QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX5QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX6QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX7QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX8QTY = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX1PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX2PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX3PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX4PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX5PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX6PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX7PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX8PRC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX1AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX2AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX3AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX4AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX5AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX6AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX7AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_FX8AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUSTID1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUSTID2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUSTID3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_CUSTID4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD21 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD22 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD31 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD32 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD41 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_LVD42 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN10TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN10AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN11TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN11AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN12TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN12AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN13TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN13AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN14TO = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_DN14AMT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_REMARK3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_REMARK4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_REMARK5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RO_REMARK6 = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Rooms", x => x.RO_CODE);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Rooms");
        }
    }
}
