using System.ComponentModel.DataAnnotations;
using System.Reflection.Emit;

namespace CD01.Models
{
    public class Room
    {
        [Key]
        public string RO_CODE { get; set; }
        public string RO_PROJ { get; set; }
        public string RO_DEPT { get; set; }
        public string RO_FLOOR { get; set; }
        public string RO_ROOM { get; set; }
        public string RO_HOMENO { get; set; }
        public string RO_TYPE { get; set; }
        public string RO_AREA { get; set; }
        public string RO_RATIO { get; set; }
        public string RO_DATEIN { get; set; }
        public string RO_SELECT { get; set; }
        public string RO_ARAMT { get; set; }
        public string RO_FLAG { get; set; }
        public string RO_BF { get; set; }
        public string RO_CR { get; set; }
        public string RO_ARNO { get; set; }
        public string RO_MEA { get; set; }
        public string RO_ELECNO { get; set; }
        public string RO_METERWT { get; set; }
        public string RO_METEREL { get; set; }
        public string RO_CARPARK { get; set; }
        public string RO_OWNER { get; set; }
        public string RO_RATE0 { get; set; }
        public string RO_CUST0 { get; set; }
        public string RO_CUST1 { get; set; }
        public string RO_CUST2 { get; set; }
        public string RO_CUST3 { get; set; }
        public string RO_CUST4 { get; set; }
        public string RO_CUST1TY { get; set; }
        public string RO_CUST2TY { get; set; }
        public string RO_CUST3TY { get; set; }
        public string RO_LEASENO { get; set; }
        public string RO_DN1TO { get; set; }
        public string RO_DN2TO { get; set; }
        public string RO_DN3TO { get; set; }
        public string RO_DN4TO { get; set; }
        public string RO_DN5TO { get; set; }
        public string RO_DN6TO { get; set; }
        public string RO_DN7TO { get; set; }
        public string RO_DN8TO { get; set; }
        public string RO_DN9TO { get; set; }
        public string RO_DN1AMT { get; set; }
        public string RO_DN2AMT { get; set; }
        public string RO_DN3AMT { get; set; }
        public string RO_DN4AMT { get; set; }
        public string RO_DN5AMT { get; set; }
        public string RO_DN6AMT { get; set; }
        public string RO_DN7AMT { get; set; }
        public string RO_DN8AMT { get; set; }
        public string RO_DN9AMT { get; set; }
        public string RO_STATUS { get; set; }
        public string RO_RTYPE { get; set; }
        public string RO_REMARK { get; set; }
        public string RO_LVNAME1 { get; set; }
        public string RO_LVADDR1 { get; set; }
        public string RO_LVTEL1 { get; set; }
        public string RO_LVID1 { get; set; }
        public string RO_LVNAME2 { get; set; }
        public string RO_LVADDR2 { get; set; }
        public string RO_LVTEL2 { get; set; }
        public string RO_LVID2 { get; set; }
        public string RO_LVNAME3 { get; set; }
        public string RO_LVADDR3 { get; set; }
        public string RO_LVTEL3 { get; set; }
        public string RO_LVID3 { get; set; }
        public string RO_LVNAME4 { get; set; }
        public string RO_LVADDR4 { get; set; }
        public string RO_LVTEL4 { get; set; }
        public string RO_LVID4 { get; set; }
        public string RO_LVNAME5 { get; set; }
        public string RO_LVADDR5 { get; set; }
        public string RO_LVTEL5 { get; set; }
        public string RO_LVID5 { get; set; }
        public string RO_LASTRC { get; set; }
        public string RO_LASTRCD { get; set; }
        public string RO_LASTRCA { get; set; }
        public string RO_DATEIN2 { get; set; }
        public string EDIT_DATE { get; set; }
        public string EDIT_TIME { get; set; }
        public string EDIT_BY { get; set; }
        public string RO_FIELD1 { get; set; }
        public string RO_FIELD2 { get; set; }
        public string RO_FIELD3 { get; set; }
        public string RO_FIELD4 { get; set; }
        public string RO_RCODE { get; set; }
        public string RO_RSTATUS { get; set; }
        public string RO_JONG { get; set; }
        public string RO_JONGD { get; set; }
        public string RO_MOVEIN { get; set; }
        public string RO_INDATE { get; set; }
        public string RO_SANYA { get; set; }
        public string RO_SANYAD { get; set; }
        public string RO_BEOUT { get; set; }
        public string RO_BEOUTD { get; set; }
        public string RO_OUT { get; set; }
        public string RO_OUTD { get; set; }
        public string RO_REMARK2 { get; set; }
        public string RO_RDATE { get; set; }
        public string RO_FX1 { get; set; }
        public string RO_FX2 { get; set; }
        public string RO_FX3 { get; set; }
        public string RO_FX4 { get; set; }
        public string RO_FX5 { get; set; }
        public string RO_FX6 { get; set; }
        public string RO_FX7 { get; set; }
        public string RO_FX8 { get; set; }
        public string RO_FX1QTY { get; set; }
        public string RO_FX2QTY { get; set; }
        public string RO_FX3QTY { get; set; }
        public string RO_FX4QTY { get; set; }
        public string RO_FX5QTY { get; set; }
        public string RO_FX6QTY { get; set; }
        public string RO_FX7QTY { get; set; }
        public string RO_FX8QTY { get; set; }
        public string RO_FX1PRC { get; set; }
        public string RO_FX2PRC { get; set; }
        public string RO_FX3PRC { get; set; }
        public string RO_FX4PRC { get; set; }
        public string RO_FX5PRC { get; set; }
        public string RO_FX6PRC { get; set; }
        public string RO_FX7PRC { get; set; }
        public string RO_FX8PRC { get; set; }
        public string RO_FX1AMT { get; set; }
        public string RO_FX2AMT { get; set; }
        public string RO_FX3AMT { get; set; }
        public string RO_FX4AMT { get; set; }
        public string RO_FX5AMT { get; set; }
        public string RO_FX6AMT { get; set; }
        public string RO_FX7AMT { get; set; }
        public string RO_FX8AMT { get; set; }
        public string RO_CUSTID1 { get; set; }
        public string RO_CUSTID2 { get; set; }
        public string RO_CUSTID3 { get; set; }
        public string RO_CUSTID4 { get; set; }
        public string RO_LVD11 { get; set; }
        public string RO_LVD12 { get; set; }
        public string RO_LVD21 { get; set; }
        public string RO_LVD22 { get; set; }
        public string RO_LVD31 { get; set; }
        public string RO_LVD32 { get; set; }
        public string RO_LVD41 { get; set; }
        public string RO_LVD42 { get; set; }
        public string RO_DN10TO { get; set; }
        public string RO_DN10AMT { get; set; }
        public string RO_DN11TO { get; set; }
        public string RO_DN11AMT { get; set; }
        public string RO_DN12TO { get; set; }
        public string RO_DN12AMT { get; set; }
        public string RO_DN13TO { get; set; }
        public string RO_DN13AMT { get; set; }
        public string RO_DN14TO { get; set; }
        public string RO_DN14AMT { get; set; }
        public string RO_REMARK3 { get; set; }
        public string RO_REMARK4 { get; set; }
        public string RO_REMARK5 { get; set; }
        public string RO_REMARK6 { get; set; }

    }
}
