// <auto-generated />
using CD01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CD01.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240214084334_CMM_ROOM")]
    partial class CMM_ROOM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CD01.Models.Room", b =>
                {
                    b.Property<string>("RO_CODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EDIT_BY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDIT_DATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDIT_TIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_ARAMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_AREA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_ARNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_BEOUT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_BEOUTD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_BF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CARPARK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST0")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST1TY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST2TY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST3TY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUST4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUSTID1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUSTID2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUSTID3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_CUSTID4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DATEIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DATEIN2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DEPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN10AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN10TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN11AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN11TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN12AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN12TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN13AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN13TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN14AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN14TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN1AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN1TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN2AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN2TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN3AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN3TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN4AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN4TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN5AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN5TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN6AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN6TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN7AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN7TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN8AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN8TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN9AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_DN9TO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_ELECNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FIELD1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FIELD2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FIELD3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FIELD4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FLAG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FLOOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX1AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX1PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX1QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX2AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX2PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX2QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX3AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX3PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX3QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX4AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX4PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX4QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX5AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX5PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX5QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX6AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX6PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX6QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX7AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX7PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX7QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX8AMT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX8PRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_FX8QTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_HOMENO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_INDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_JONG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_JONGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LASTRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LASTRCA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LASTRCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LEASENO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVADDR1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVADDR2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVADDR3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVADDR4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVADDR5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD31")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD32")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD41")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVD42")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVID1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVID2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVID3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVID4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVID5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVNAME1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVNAME2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVNAME3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVNAME4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVNAME5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVTEL1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVTEL2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVTEL3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVTEL4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_LVTEL5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_MEA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_METEREL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_METERWT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_MOVEIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_OUT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_OUTD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_OWNER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_PROJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_RATE0")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_RATIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_RCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_RDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_REMARK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_REMARK2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_REMARK3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_REMARK4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_REMARK5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_REMARK6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_ROOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_RSTATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_RTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_SANYA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_SANYAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_SELECT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RO_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RO_CODE");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
